### ISSUE TITLE
Little double quote issue

### ISSUE THREAD

**Issue by huseynsnmz** [TH3xACE/SUDO_KILLER#1]
**Describe the bug**
There is a problem with if condition in SUDO_KILLERv1.3.2.sh.

**To Reproduce**
../SUDO_KILLERv1.3.2.sh -c -r report.txt -e /tmp/

**Problem**
============ Checking for disclosed vulnerabilities related to version used (CVE) ==================  

[+] Sudo version vulnerable to the following CVEs:
./SUDO_KILLERv1.3.2.sh: line 266: [: too many arguments

**To solve**
I added double quote to a variable.

It was like that:
if [ $cvepath ]; then ...

I changed it like this:
if [ "$cvepath" ]; then ...

It is not a big issue actually and issue is very simple but I still wanted to write it and it's solution. Thank you for this awesome project :)

**Comment by TH3xACE** [comment]
Hi huseynsnmz,

Thank you for the issue which is now corrected. You are welcome, I am happy that I contributed to the community in my way and that there are positive feedback. :) I will update the docker in the coming days...

Regards.
