### ISSUE TITLE
Checking for Missing scripts from sudoers

### ISSUE THREAD

**Issue by b0x-Protector** [TH3xACE/SUDO_KILLER#10]
I think that the line 469 should look as follow:

`if [ "$sudonopassuser" ]; then`
`  echo '' |sudo -S -l -k | sed 's/(root) //g' | sed 's/NOPASSWD: //g' | sed 's/,/\n/g'  | sed -e 's/  *$//' | awk '$1=$1' | cut -d " " -f 1 | grep .sh  > /tmp/script_list`
`  echo -e "${BOLD}${GREEN}[+] The script/s found in sudoers can be found at: /tmp/script_list 
 ${RESET}"`
`fi`

**Comment by TH3xACE** [comment]
the code that you propose will not work as intended since it will check for only one if NOPASSWD is present in the sudo's rules, only once.... the check should be done for every script... but you are right about something... there is a missing check... I will make the amendment. :) Thank you.

**Comment by b0x-Protector** [comment]
Based on the comment "_#### check for scripts execution without password in sudoers_", it seemed to me that we can use the result obtained earlier, in order not to enter the password manually again.

At first I thought of modifying the string as follows:
```
touch /tmp/script_list #for compatibility with future checks
if [ "$sudonopassuser" ] || [ "$sudoauth" ]; then
  if [ "$sudonopassuser" ]; then
    echo "" |sudo -S -l -k | grep "NOPASSWD" | sed 's/(root) //g' | sed 's/NOPASSWD: //g' | sed 's/,/\n/g'  | sed -e 's/  *$//' | awk '$1=$1' | cut -d " " -f 1 | grep .sh  >> /tmp/script_list
    echo -e "${BOLD}${GREEN}[+] The script/s found in sudoers can be found at: /tmp/script_list ${RESET}"
  fi
  if [ "$sudoauth" ]; then
    echo $userpassword |sudo -S -l -k | grep "NOPASSWD" | sed 's/(root) //g' | sed 's/NOPASSWD: //g' | sed 's/,/\n/g'  | sed -e 's/  *$//' | awk '$1=$1' | cut -d " " -f 1 | grep .sh  >> /tmp/script_list
   echo -e "${BOLD}${GREEN}[+] The script/s found in sudoers can be found at: /tmp/script_list ${RESET}"
  fi
fi
```
But if I understood correctly, only sudo without password is checked here.
Not at all :)
