### ISSUE TITLE
I'm always frustrated when the phone version changes and chrome acts weird when maps keep something hidden 

### ISSUE THREAD

**Issue by BIGB69666** [TH3xACE/SUDO_KILLER#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BIGB69666** [comment]
Languages and country are hard to find sometimes but I am new on my android so I hope I'll figure it out

**Comment by TH3xACE** [comment]
Hello,

Is your issue related to the project SUDO_KILLER ? I can't figure out the relationship you are having with ?

**Comment by TH3xACE** [comment]
I think you wanted to create an issue on this project [Blankj / AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode) rather than on mine
