### ISSUE TITLE
Lost in translation

### ISSUE THREAD

**Issue by manymenwish** [TH3xACE/SUDO_KILLER#20]
**Is your feature request related to a problem? 
   Yes, it seems that we've come to an end and much awaited for.
Please describe.** what's the safe word?
Past the point of please stop, explain yourself please.

**Describe the solution you'd like**
To do what ever I can do to get these bastards off of us.

**Describe alternatives you've considered**

**Additional context**

**Comment by TH3xACE** [comment]
What’s the issue ? Can you be more explicit?
