### ISSUE TITLE
Missing scripts checking out arguments

### ISSUE THREAD

**Issue by lazytanuki** [TH3xACE/SUDO_KILLER#3]
**Describe the bug**
The missing scripts function parses the whole command as one file. If the command is `/usr/bin/cat somefile` the program will check for the existence of `/usr/bin/catsomefile`

**To Reproduce**
1. Insert the following command in a sudoer rule : `/usr/bin/cat somefile`

**Expected behavior**
I think it would be appropriate to only check if the binary exists except if the binary is an interpreter. in which case the presence of the file should be checked

**Side note**
I want to say that you've done some really great work, thank you ! :)

**Comment by TH3xACE** [comment]
Hi,

Thank you for the issue. I have currently no access to a PC but I will check it out as soon as I'm back home. I will leave the issue open till then. 

Thank you also for your message,  I am happy to see that people are interested by the tool and are also contributing to help me improve it. If you have the fix just send a pull request if not will correct it asap.

Regards, 
Ace.

**Comment by TH3xACE** [comment]
Bug corrected... Thanks for the issue :)
