### ISSUE TITLE
Checking sudo without password

### ISSUE THREAD

**Issue by b0x-Protector** [TH3xACE/SUDO_KILLER#9]
I suppose the line 331 should be started with "sudonopassuser=" not "sudonopassuser=="

P.S. 
Why are you using the GREP at the end? Maybe one is enough?

**Comment by TH3xACE** [comment]
Hi b0x-Protector,

I think it was a mistype but the result is the same, "=" is like equal and '==' is like match.

Thanks for your issue, despite not being a bug, I will change it to "="... to keep some sort of consistency and easy reading.

regards,
TH3xACE.

**Comment by TH3xACE** [comment]
for the grep... I think you are right. I forget why, I included the second one... will comment it for now..

**Comment by b0x-Protector** [comment]
> Hi b0x-Protector,
> 
> I think it was a mistype but the result is the same, "=" is like equal and '==' is like match.
> 
> Thanks for your issue, despite not being a bug, I will change it to "="... to keep some sort of consistency and easy reading.
> 
> regards,
> TH3xACE.

Unfortunately, my bash does not understand "==" :(

Thanks you for SUDO_KILLER

**Comment by TH3xACE** [comment]
> > Hi b0x-Protector,
> > I think it was a mistype but the result is the same, "=" is like equal and '==' is like match.
> > Thanks for your issue, despite not being a bug, I will change it to "="... to keep some sort of consistency and easy reading.
> > regards,
> > TH3xACE.
> 
> Unfortunately, my bash does not understand "==" :(
> 
> Thanks you for SUDO_KILLER

I see, too bad :( in the docker and on my host it went fine, I just tested it but I just made the modification..  should be fine now :).

You are welcome, feel free if you find any other issue, want to contribute or else...

regards,
TH3xACE.
